version: 5
daemon:
  log_level: info
  admin_user: izaac
  admin_group: wheel
  disable_clocks_cleanup: false
apply_settings_timer: 5
gpus:
  '1002:7550-148C:2435-0000:03:00.0':
    fan_control_enabled: false
    pmfw_options:
      acoustic_target: 946
      zero_rpm: true
    performance_level: auto
    min_memory_clock: 1400
    max_memory_clock: 1400
    voltage_offset: -80
current_profile: null
auto_switch_profiles: false
